import type { LucideIcon } from 'lucide-react';
import { Flame, HardHat, ShieldAlert, Brain, Cog, Zap, Wind, Eye, Droplets, Activity } from 'lucide-react';

export type ModuleInfo = { id:string; name:string; short:string; description:string; icon:LucideIcon; status:string; risk:string; value:string; progress:number; lessons:string; image:string; tint:string };
export const modules:ModuleInfo[] = [
  {id:'fire',name:'Fire & Explosion',short:'Fire Detection',description:'Recognize fire, smoke and evacuation risks in industrial environments.',icon:Flame,status:'ACTIVE',risk:'HIGH',value:'2 active alerts',progress:82,lessons:'4 / 5 lessons',image:'photo-1516937941344-00b4e0337589',tint:'orange'},
  {id:'ppe',name:'PPE Safety',short:'PPE Detection',description:'Build consistent habits around personal protective equipment.',icon:HardHat,status:'ACTIVE',risk:'LOW',value:'94% compliance',progress:100,lessons:'5 / 5 lessons',image:'photo-1581092160562-40aa08e78837',tint:'blue'},
  {id:'risk',name:'Risk Awareness',short:'Risk Detection',description:'Identify contributing factors and assess workplace hazards.',icon:ShieldAlert,status:'MONITORING',risk:'MEDIUM',value:'68 risk score',progress:46,lessons:'2 / 5 lessons',image:'photo-1581092580497-e0d23cbdf1dc',tint:'yellow'},
  {id:'fatigue',name:'Fatigue & Human Factors',short:'Fatigue Detection',description:'Explore attention, workload and fatigue indicators in context.',icon:Brain,status:'DEMO READY',risk:'LOW',value:'No indicators',progress:35,lessons:'1 / 4 lessons',image:'photo-1504307651254-35680f356dfd',tint:'purple'},
  {id:'machinery',name:'Machinery Safety',short:'Machinery Safety',description:'Understand machine zones, guarding and worker proximity.',icon:Cog,status:'ACTIVE',risk:'MEDIUM',value:'1 zone alert',progress:58,lessons:'3 / 5 lessons',image:'photo-1567789884554-0b844b597180',tint:'cyan'},
  {id:'electrical',name:'Electrical Safety',short:'Electrical Safety',description:'Practice awareness around panels, equipment and restricted areas.',icon:Zap,status:'ACTIVE',risk:'LOW',value:'All clear',progress:24,lessons:'1 / 5 lessons',image:'photo-1473341304170-971dacb5ac1e',tint:'yellow'},
];
export type Scenario = {id:string;module:string;title:string;description:string;difficulty:string;duration:string;objective:string;image:string;hazards:string[]};
export const scenarios:Scenario[] = [
  {id:'fire-01',module:'fire',title:'Fire in Production Area',description:'Smoke is reported near an active production line.',difficulty:'Beginner',duration:'8 min',objective:'Identify hazards and choose a safe response.',image:'photo-1516937941344-00b4e0337589',hazards:['Smoke near production line','Blocked exit route','Manual alarm point']},
  {id:'ppe-01',module:'ppe',title:'PPE Check: Workshop Entry',description:'Review a team preparing to enter the workshop.',difficulty:'Beginner',duration:'6 min',objective:'Spot missing and incorrectly worn equipment.',image:'photo-1581092160562-40aa08e78837',hazards:['Missing eye protection','Loose safety vest','Unsecured footwear']},
  {id:'gas-01',module:'risk',title:'Gas Leak: Confined Space',description:'A simulated gas indicator activates near a vessel.',difficulty:'Intermediate',duration:'10 min',objective:'Recognize exposure and access risks.',image:'photo-1581092580497-e0d23cbdf1dc',hazards:['Gas indicator alert','Restricted entry','Ventilation status']},
  {id:'machine-01',module:'machinery',title:'Machinery Proximity',description:'A worker approaches a marked machine zone.',difficulty:'Intermediate',duration:'7 min',objective:'Identify the zone boundary and safe next step.',image:'photo-1567789884554-0b844b597180',hazards:['Worker near machine','Guard status indicator','Restricted zone marker']},
];
export const activity = [
  {title:'PPE Assessment completed',detail:'Score 92% · Workshop Entry',time:'Today, 10:42 AM',icon:HardHat,color:'blue'},
  {title:'Fire AR Scenario started',detail:'Fire in Production Area',time:'Yesterday, 3:18 PM',icon:Flame,color:'orange'},
  {title:'Fire Learn section completed',detail:'4 of 5 lessons complete',time:'Sep 22, 2026',icon:Eye,color:'cyan'},
  {title:'Safety Aware badge earned',detail:'First steps in safety learning',time:'Sep 20, 2026',icon:ShieldAlert,color:'green'},
];
export const achievements = [{name:'Fire Ready',detail:'Completed your first fire safety scenario',icon:Flame,color:'orange'},{name:'PPE Aware',detail:'Achieved 90% or more in a PPE assessment',icon:HardHat,color:'blue'},{name:'Safety Champion',detail:'Practiced across four learning modules',icon:Activity,color:'green'},{name:'First Assessment',detail:'Completed your first knowledge check',icon:Eye,color:'purple'}];
export const certificates = [{name:'Fire Safety Training',date:'12 Aug 2026',id:'DEMO-FIRE-0826',module:'Fire & Explosion'},{name:'PPE Awareness',date:'04 Jul 2026',id:'DEMO-PPE-0726',module:'PPE Safety'}];
export const chartData = [{day:'Mon',score:62},{day:'Tue',score:70},{day:'Wed',score:66},{day:'Thu',score:78},{day:'Fri',score:73},{day:'Sat',score:88},{day:'Sun',score:82}];
export const chartDataMonth = [{day:'W1',score:55},{day:'W2',score:64},{day:'W3',score:68},{day:'W4',score:82}];
export const systemMetrics = [{label:'Workers monitored',value:'24',icon:Activity},{label:'Active alerts',value:'03',icon:ShieldAlert},{label:'System status',value:'DEMO MODE',icon:Wind},{label:'Sync status',value:'LOCAL ONLY',icon:Droplets}];
export const en = {home:'Home',modules:'Modules',training:'AR Training',simulator:'Simulator',progress:'Progress',continue:'Continue Training',startAr:'Start AR Training',viewAll:'View all',open:'Open module',recommended:'Recommended for you',recent:'Recent activity',achievements:'Achievements',quickActions:'Quick actions',offline:'Offline demo',search:'Search modules...',start:'Start scenario',next:'Next step',reset:'Reset',run:'Run simulation',save:'Save scenario',saved:'Saved scenarios',compare:'Compare scenarios',loading:'Running demonstration model…',close:'Close',complete:'Complete scenario',hint:'Show hint',replay:'Replay instruction',voice:'Voice guidance',language:'Language',demo:'DEMO DATA',completion:'Overall progress'};
export const hi:Record<string,string> = {home:'होम',modules:'मॉड्यूल',training:'AR प्रशिक्षण',simulator:'सिम्युलेटर',progress:'प्रगति',continue:'प्रशिक्षण जारी रखें',startAr:'AR प्रशिक्षण शुरू करें',viewAll:'सभी देखें',recommended:'आपके लिए सुझाव',recent:'हाल की गतिविधि',achievements:'उपलब्धियाँ',quickActions:'त्वरित कार्रवाई',search:'मॉड्यूल खोजें...',start:'परिदृश्य शुरू करें',next:'अगला चरण',reset:'रीसेट',run:'सिमुलेशन चलाएँ',save:'परिदृश्य सहेजें',saved:'सहेजे गए परिदृश्य',compare:'परिदृश्यों की तुलना',loading:'डेमो मॉडल चल रहा है…',close:'बंद करें',language:'भाषा',demo:'डेमो डेटा',completion:'कुल प्रगति'};
export const sat:Record<string,string> = {home:'ᱚᱲᱟᱜ',modules:'ᱢᱚᱰᱭᱩᱞ',training:'AR ᱥᱤᱠᱷᱱᱟ',simulator:'ᱥᱤᱢᱩᱞᱮᱴᱚᱨ',progress:'ᱞᱟᱦᱟ',continue:'ᱥᱤᱠᱷᱱᱟ ᱞᱮᱛᱟᱲ',startAr:'AR ᱥᱤᱠᱷᱱᱟ ᱮᱦᱚᱵ',viewAll:'ᱡᱚᱛᱚ ᱧᱮᱞ',recommended:'ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱥᱚᱞᱦᱟ',recent:'ᱱᱤᱛᱚᱜ ᱠᱟᱹᱢᱤ',achievements:'ᱡᱤᱛᱠᱟᱹᱨ',quickActions:'ᱞᱟᱹᱜᱤᱫ ᱠᱟᱹᱢᱤ',search:'ᱢᱚᱰᱭᱩᱞ ᱥᱮᱸᱫᱽᱨᱟ...',start:'ᱥᱤᱠᱷᱱᱟ ᱮᱦᱚᱵ',next:'ᱤᱱᱟᱹᱜ ᱫᱷᱟᱯ',reset:'ᱫᱚᱦᱲᱟ',run:'ᱥᱤᱢᱩᱞᱮᱴᱚᱨ ᱪᱟᱹᱞᱩ',save:'ᱥᱤᱠᱷᱱᱟ ᱵᱟᱹᱭ',saved:'ᱵᱟᱹᱭᱟᱠᱟᱱ',compare:'ᱛᱩᱞᱟᱹ ᱢᱮ',loading:'ᱰᱮᱢᱳ ᱪᱟᱹᱞᱩ ᱠᱟᱱᱟ…',close:'ᱵᱚᱸᱫ',language:'ᱯᱟᱹᱨᱥᱤ',demo:'ᱰᱮᱢᱳ ᱰᱟᱴᱟ',completion:'ᱢᱩᱪᱟᱹᱫ'};
